import { getCurrentSession, onAuthStateChange } from "./auth.js?v=20260825r1";
import { initResourceShell } from "./resource-shell.js";
import { checkCurrentAdmin, fetchAdminAnalytics, fetchAdminCategories, fetchAdminResources, saveAdminResource, setResourceArchived, setResourcePublished, updateCategory } from "./admin-data.js";

const state={authorized:false,analytics:null,resources:[],categories:[],users:[],editing:null,windowDays:30,userQuery:""};
const titles={overview:"Overview",resources:"Resources",editor:"Resource editor",categories:"Categories",users:"Users",analytics:"Analytics"};
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(typeof text==="string")n.textContent=text;return n;}
function visible(selector,show){const n=document.querySelector(selector);if(n)n.hidden=!show;}
function fmt(value){return new Intl.NumberFormat("en").format(Number(value)||0);}
function date(value){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en",{year:"numeric",month:"short",day:"numeric"}).format(d);}
function setStatus(message){const n=document.querySelector("[data-admin-status]");if(n)n.textContent=message;}
function showAccess(name){visible("[data-admin-checking]",name==="checking");visible("[data-admin-signed-out]",name==="signed-out");visible("[data-admin-denied]",name==="denied");visible("[data-admin-auth-error]",name==="error");visible("[data-admin-shell]",name==="authorized");}
function showModule(name){document.querySelectorAll("[data-admin-module]").forEach(n=>n.hidden=n.dataset.adminModule!==name);document.querySelectorAll("[data-admin-tab]").forEach(b=>{if(b.dataset.adminTab===name)b.setAttribute("aria-current","page");else b.removeAttribute("aria-current")});document.querySelector("[data-admin-section-title]").textContent=titles[name]||"Admin";location.hash=name==="overview"?"":name;document.querySelector("[data-admin-nav]")?.classList.remove("is-open");document.querySelector("[data-admin-menu]")?.setAttribute("aria-expanded","false");}
function metric(label,value){const n=el("article","admin-metric");n.append(el("span","",label),el("strong","",fmt(value)));return n;}
function renderOverview(){const o=state.analytics.overview||{};const box=document.querySelector("[data-overview-metrics]");box.replaceChildren(metric("Total users",o.total_users),metric("New / 7d",o.new_users_7d),metric("New / 30d",o.new_users_30d),metric("Published",o.published_resources),metric("Drafts",o.draft_resources),metric("Archived",o.archived_resources),metric("Total saves",o.total_saves),metric("Downloads",o.total_downloads),metric("Window",`${o.window_days||state.windowDays}d`));const insights=document.querySelector("[data-content-insights]");insights.replaceChildren();const resource=[...state.analytics.resources].sort((a,b)=>(Number(b.recent_saves)+Number(b.recent_downloads))-(Number(a.recent_saves)+Number(a.recent_downloads)))[0];const category=[...state.analytics.categories].sort((a,b)=>(Number(b.recent_saves)+Number(b.recent_downloads))-(Number(a.recent_saves)+Number(a.recent_downloads)))[0];const messages=[];if(resource&&(Number(resource.recent_saves)+Number(resource.recent_downloads))>0)messages.push(`${resource.title} leads resource engagement with ${fmt(Number(resource.recent_saves)+Number(resource.recent_downloads))} saves plus downloads in this window.`);if(category&&(Number(category.recent_saves)+Number(category.recent_downloads))>0)messages.push(`${category.category_name} is the leading category in this window.`);if(!messages.length)messages.push("No engagement events exist for this window yet. Publish useful resources and review again after genuine activity.");messages.forEach(m=>insights.append(el("p","",m)));const activity=document.querySelector("[data-recent-activity]");activity.replaceChildren();if(!state.analytics.activity.length)activity.append(el("li","","No recent account or resource activity."));else state.analytics.activity.forEach(a=>activity.append(el("li","",`${a.actor_name} ${a.activity_type}${a.resource_title?` ${a.resource_title}`:""} · ${date(a.occurred_at)}`)));document.querySelector("[data-module-loading]").hidden=true;document.querySelector("[data-module-content]").hidden=false;}
function recordMeta(parent,label,value){const group=el("div");group.append(el("dt","",label),el("dd","",String(value??"—")));parent.append(group);}
function renderResources(){const root=document.querySelector("[data-admin-resources]");root.replaceChildren();state.resources.forEach(r=>{const archived=Boolean(r.archived_at);const status=archived?"ARCHIVED":r.published?"PUBLISHED":"DRAFT";const card=el("article","admin-record");card.append(el("p","admin-record__meta",`${status} / ${r.file_type?.toUpperCase()||"FILE"}`),el("h3","",r.title));const dl=el("dl");recordMeta(dl,"Slug",r.slug);recordMeta(dl,"Updated",date(r.updated_at));recordMeta(dl,"Published",date(r.published_at));recordMeta(dl,"Archived",date(r.archived_at));card.append(dl);const actions=el("div","admin-record__actions");const edit=el("button","","Edit");edit.type="button";edit.onclick=()=>openEditor(r);actions.append(edit);if(archived){const restore=el("button","","Restore to draft");restore.type="button";restore.onclick=async()=>{restore.disabled=true;try{await setResourceArchived(r.id,false);await loadResources();setStatus("Resource restored as a draft.");}catch{setStatus("Resource could not be restored.");restore.disabled=false}};actions.append(restore);}else{const stateButton=el("button","",r.published?"Unpublish":"Publish");stateButton.type="button";stateButton.onclick=async()=>{stateButton.disabled=true;try{await setResourcePublished(r.id,!r.published);await loadResources();setStatus(r.published?"Resource unpublished.":"Resource published.");}catch{setStatus("Resource state could not be changed.");stateButton.disabled=false}};const archive=el("button","","Archive");archive.type="button";archive.onclick=async()=>{if(!window.confirm(`Archive ${r.title}? Public discovery and new downloads will stop, while history is preserved.`))return;archive.disabled=true;try{await setResourceArchived(r.id,true);await loadResources();setStatus("Resource archived. Historical bookmarks, downloads and analytics were preserved.");}catch{setStatus("Resource could not be archived.");archive.disabled=false}};actions.append(stateButton,archive);}card.append(actions);root.append(card)});document.querySelector("[data-resources-state]").hidden=state.resources.length>0;document.querySelector("[data-resources-state]").textContent=state.resources.length?"":"No resources exist. Create a draft and upload an approved file.";root.hidden=false;}
function fillCategorySelect(){const select=document.querySelector("[name=category_id]");select.replaceChildren(el("option","","Choose category"));select.firstElementChild.value="";state.categories.forEach(c=>{const o=el("option","",c.name);o.value=c.id;select.append(o)});}
function openEditor(resource=null){state.editing=resource;const form=document.querySelector("[data-resource-form]");form.reset();fillCategorySelect();for(const name of ["id","title","slug","teaser","description","category_id","author"]){if(resource&&form.elements[name])form.elements[name].value=resource[name]||"";}form.elements.tags.value=resource?.tags?.join(", ")||"";const archived=Boolean(resource?.archived_at);form.elements.published.checked=Boolean(resource?.published);form.elements.published.disabled=archived;form.querySelector('[name="intent"][value="publish"]').disabled=archived;document.querySelector("[data-editor-title]").textContent=resource?`Edit ${resource.title}${archived?" (archived)":""}`:"Create resource draft";showModule("editor");}
async function loadResources(){state.resources=await fetchAdminResources();renderResources();}
function renderCategories(){const root=document.querySelector("[data-admin-categories]");root.replaceChildren();state.categories.forEach(c=>{const form=el("form","admin-record admin-category-form");form.dataset.categoryId=c.id;form.append(el("p","admin-record__meta",`${c.slug} / ${c.resources?.[0]?.count||0} resources`),el("h3","",c.name));const description=el("textarea");description.name="description";description.value=c.description||"";description.setAttribute("aria-label",`${c.name} description`);const order=el("input");order.name="sort_order";order.type="number";order.value=c.sort_order;order.setAttribute("aria-label",`${c.name} display order`);const button=el("button","button button--secondary","Save category metadata");button.type="submit";form.append(description,order,button);form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{await updateCategory(c.id,{description:description.value,sortOrder:order.value});setStatus(`${c.name} metadata updated.`);}catch{setStatus("Category metadata could not be updated.");}finally{button.disabled=false}};root.append(form)});}
function renderUsers(){const root=document.querySelector("[data-admin-users]");root.replaceChildren();const q=state.userQuery.toLowerCase();const users=state.analytics.users.filter(u=>String(u.display_name).toLowerCase().includes(q));if(!users.length){root.append(el("p","admin-module-state","No matching user accounts."));return;}users.forEach(u=>{const card=el("article","admin-record");card.append(el("p","admin-record__meta","ACCOUNT / SUMMARY"),el("h3","",u.display_name||"Unnamed account"));const dl=el("dl");recordMeta(dl,"Joined",date(u.joined_at));recordMeta(dl,"Saved",fmt(u.total_saves));recordMeta(dl,"Downloads",fmt(u.total_downloads));recordMeta(dl,"Last resource activity",date(u.last_resource_activity));card.append(dl);root.append(card)});}
function ranked(rootSelector,items,nameKey){const root=document.querySelector(rootSelector);root.replaceChildren();if(!items.length){root.append(el("p","","No records available."));return;}items.forEach(i=>{const row=el("div","admin-ranked-row");row.append(el("strong","",i[nameKey]),el("p","",`${fmt(i.total_saves)} saves · ${fmt(i.total_downloads)} downloads · ${fmt(Number(i.total_saves)+Number(i.total_downloads))} combined`));root.append(row)});}
function renderAnalytics(){const trend=document.querySelector("[data-admin-trend]");trend.replaceChildren();const max=Math.max(1,...state.analytics.trend.map(d=>Number(d.saves)+Number(d.downloads)));state.analytics.trend.forEach(d=>{const count=Number(d.saves)+Number(d.downloads);const bar=el("span","admin-trend__day");bar.style.height=`${Math.max(2,count/max*100)}%`;bar.title=`${d.activity_day}: ${count} events`;trend.append(bar)});ranked("[data-resource-metrics]",state.analytics.resources,"title");ranked("[data-category-metrics]",state.analytics.categories,"category_name");}
async function loadAuthorizedData(){setStatus("Loading authorized admin data…");try{const [analytics,resources,categories]=await Promise.all([fetchAdminAnalytics(state.windowDays),fetchAdminResources(),fetchAdminCategories()]);state.analytics=analytics;state.resources=resources;state.categories=categories;renderOverview();renderResources();renderCategories();renderUsers();renderAnalytics();setStatus("Admin data loaded.");}catch{setStatus("Authorized admin data could not be loaded.");document.querySelectorAll(".admin-module-state").forEach(n=>n.textContent="This module is unavailable. No values have been fabricated.");}}
async function resolveAccess(session){if(!session){state.authorized=false;showAccess("signed-out");return;}showAccess("checking");try{state.authorized=await checkCurrentAdmin();if(!state.authorized){showAccess("denied");return;}showAccess("authorized");showModule((location.hash.slice(1)in titles)?location.hash.slice(1):"overview");await loadAuthorizedData();}catch{showAccess("error");}}

document.querySelector("[data-admin-menu]")?.addEventListener("click",e=>{const nav=document.querySelector("[data-admin-nav]");const open=nav.classList.toggle("is-open");e.currentTarget.setAttribute("aria-expanded",String(open))});
document.querySelectorAll("[data-admin-tab]").forEach(b=>b.addEventListener("click",()=>showModule(b.dataset.adminTab)));
document.querySelector("[data-new-resource]")?.addEventListener("click",()=>openEditor());document.querySelector("[data-close-editor]")?.addEventListener("click",()=>showModule("resources"));
document.querySelector("[name=title]")?.addEventListener("input",e=>{const slug=document.querySelector("[name=slug]");if(!state.editing&&!slug.dataset.touched)slug.value=e.target.value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")});document.querySelector("[name=slug]")?.addEventListener("input",e=>{e.target.dataset.touched="true"});
document.querySelector("[data-resource-form]")?.addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget;const status=form.querySelector("[data-form-status]");if(!form.reportValidity())return;const submitter=e.submitter;const publish=submitter?.value==="publish"||form.elements.published.checked;const tags=form.elements.tags.value.split(",").map(x=>x.trim()).filter(Boolean);if(tags.length>20){status.textContent="Use no more than 20 tags.";return;}const values={...state.editing,id:form.elements.id.value||state.editing?.id||"",title:form.elements.title.value.trim(),slug:form.elements.slug.value.trim(),teaser:form.elements.teaser.value.trim(),description:form.elements.description.value.trim(),category_id:form.elements.category_id.value,author:form.elements.author.value.trim(),tags,published:publish};const file=form.elements.file.files[0]||null;form.querySelectorAll("button").forEach(b=>b.disabled=true);status.textContent="Saving resource…";try{await saveAdminResource(values,file);status.textContent=publish?"Resource published.":"Draft saved.";await loadResources();showModule("resources");}catch(error){const code=error instanceof Error?error.message:"";status.textContent=code==="FILE_REQUIRED"?"A file is required for a new draft.":code==="FILE_TOO_LARGE"?"File exceeds 50 MB.":code==="FILE_TYPE_INVALID"?"Use PDF, DOCX, Markdown or ZIP.":code==="SLUG_NOT_UNIQUE"?"That slug is already in use.":"Resource could not be saved.";}finally{form.querySelectorAll("button").forEach(b=>b.disabled=false)}});
document.querySelector("[data-user-search]")?.addEventListener("input",e=>{state.userQuery=e.target.value;renderUsers()});document.querySelector("[data-admin-window]")?.addEventListener("change",async e=>{state.windowDays=Number(e.target.value);if(state.authorized){setStatus("Updating analytics window…");try{state.analytics=await fetchAdminAnalytics(state.windowDays);renderOverview();renderUsers();renderAnalytics();setStatus("Analytics window updated.");}catch{setStatus("The analytics window could not be updated. Existing values were preserved.");}}});
await initResourceShell();onAuthStateChange(resolveAccess);if(!getCurrentSession())showAccess("signed-out");
