import { getSupabaseClient } from "./supabase-client.js";

const BUCKET = "resources";
const MAX_FILE_BYTES = 50 * 1024 * 1024;
const FILE_TYPES = {
  pdf: { mime: "application/pdf", allowed: ["application/pdf"] },
  docx: { mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", allowed: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
  md: { mime: "text/markdown", allowed: ["text/markdown", "text/plain"] },
  zip: { mime: "application/zip", allowed: ["application/zip", "application/x-zip-compressed"] },
};

function client() { const value=getSupabaseClient(); if(!value) throw new Error("ADMIN_NOT_CONFIGURED"); return value; }
export async function checkCurrentAdmin(){const{data,error}=await client().rpc("current_user_is_admin");if(error)throw new Error("ADMIN_CHECK_FAILED");return data===true;}
export async function fetchAdminAnalytics(days=30){const db=client();const calls=await Promise.all([db.rpc("admin_overview",{window_days:days}),db.rpc("admin_resource_metrics",{window_days:days}),db.rpc("admin_category_metrics",{window_days:days}),db.rpc("admin_user_summaries"),db.rpc("admin_engagement_trend",{window_days:days}),db.rpc("admin_recent_activity",{activity_limit:20})]);if(calls.some(x=>x.error))throw new Error("ADMIN_ANALYTICS_FAILED");return{overview:calls[0].data||{},resources:calls[1].data||[],categories:calls[2].data||[],users:calls[3].data||[],trend:calls[4].data||[],activity:calls[5].data||[]};}
export async function fetchAdminResources(){const{data,error}=await client().from("resources").select("id,slug,title,teaser,description,category_id,file_path,file_type,mime_type,author,tags,published,published_at,archived_at,created_at,updated_at").order("updated_at",{ascending:false});if(error)throw new Error("ADMIN_RESOURCES_FAILED");return data||[];}
export async function fetchAdminCategories(){const{data,error}=await client().from("categories").select("id,slug,name,description,sort_order,resources(count)").order("sort_order");if(error)throw new Error("ADMIN_CATEGORIES_FAILED");return data||[];}

function inspectFile(file){if(!file)return null;if(file.size>MAX_FILE_BYTES)throw new Error("FILE_TOO_LARGE");const extension=(file.name.split(".").pop()||"").toLowerCase();const rule=FILE_TYPES[extension];if(!rule||(file.type&&!rule.allowed.includes(file.type)))throw new Error("FILE_TYPE_INVALID");return{extension,fileType:extension,mimeType:rule.mime};}
async function uploadFile(resourceId,file){const inspected=inspectFile(file);const safeName=`${Date.now()}-${crypto.randomUUID().slice(0,8)}.${inspected.extension}`;const path=`${resourceId}/${safeName}`;const{error}=await client().storage.from(BUCKET).upload(path,file,{contentType:inspected.mimeType,upsert:false});if(error)throw new Error("UPLOAD_FAILED");return{path,...inspected};}
export async function saveAdminResource(values,file){const db=client();const isNew=!values.id;const id=values.id||crypto.randomUUID();let uploaded=null;let oldPath=values.file_path||"";if(file)uploaded=await uploadFile(id,file);if(isNew&&!uploaded)throw new Error("FILE_REQUIRED");const payload={id,slug:values.slug,title:values.title,teaser:values.teaser,description:values.description||null,category_id:values.category_id,author:values.author||null,tags:values.tags,published:Boolean(values.published),published_at:values.published?(values.published_at||new Date().toISOString()):(values.archived_at?values.published_at||null:null),file_path:uploaded?.path||oldPath,file_type:uploaded?.fileType||values.file_type,mime_type:uploaded?.mimeType||values.mime_type};const operation=isNew?db.from("resources").insert(payload).select().single():db.from("resources").update(payload).eq("id",id).select().single();const{data,error}=await operation;if(error){if(uploaded)await db.storage.from(BUCKET).remove([uploaded.path]);throw new Error(error.code==="23505"?"SLUG_NOT_UNIQUE":"RESOURCE_SAVE_FAILED");}if(uploaded&&oldPath&&oldPath!==uploaded.path)await db.storage.from(BUCKET).remove([oldPath]);return data;}
export async function setResourcePublished(resourceId,published){let query=client().from("resources").update({published,published_at:published?new Date().toISOString():null}).eq("id",resourceId);if(published)query=query.is("archived_at",null);const{data,error}=await query.select("id").maybeSingle();if(error||!data)throw new Error("RESOURCE_STATE_FAILED");}
export async function setResourceArchived(resourceId,archived){const{data,error}=await client().from("resources").update({published:false,archived_at:archived?new Date().toISOString():null}).eq("id",resourceId).select("id").maybeSingle();if(error||!data)throw new Error("RESOURCE_ARCHIVE_FAILED");}
export async function updateCategory(categoryId,{description,sortOrder}){const{error}=await client().from("categories").update({description:description||null,sort_order:Number(sortOrder)}).eq("id",categoryId);if(error)throw new Error("CATEGORY_UPDATE_FAILED");}
